baseurl = "http://blog.hujiale.me/"
languageCode = "en-us"
title = "moo..."
theme = "hemingway2"
googleAnalytics = "UA-57201547-1"
disqusShortname = "hujiale"
description = "hujiale's 20% life and 80% tech"
keywords = ["Web", "Program", "Philosophy"]

[taxonomies]
tag = "tags"
category = "categories"

[params]

[params.highlight]
style = "github"
languages = ["typescript", "go", "dockerfile", "yaml"]

[[params.social]]
url = "https://github.com/elaijuh"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/hjiale"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://www.linkedin.com/in/jiale-hu-22106632/"
fa_icon = "fa-linkedin"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
