baseurl = "http://elaijuh.github.io/"
languageCode = "en-us"
title = "moo..."
theme= "hugo-theme-geppaku"
googleAnalytics = "UA-57201547-1"
disqusShortname = ""

[author]
    # If you want to display author information set these
    # This is Optional values
    name = "Jiale HU"

    # Please set account ids
    # This is Optional values
    twitter  = "hjiale"
    linkedin = "jiale-hu-22106632"
    github   = "elaijuh"

[params]
    [params.sharebutton]
        # If you want to display share buttons set these
        # This is Optional values
        twitter  = true
        facebook = true 
        # hatena   = true # hatena is Japanese social media
        google   = true
        pocket   = true
        # Please set id when you want to display facebook
        facebookAppId = "your app id"

    [params.adsense]
        # If you want to display Google adsense set these
        # This is Optional values
        # 1. Create file written of the adsense tag into the directory "layouts/partials"
        # 2. Please set file path name omitted "layouts/partials"
        # sidebar = "adsense/sidebar.html"
        # content = "adsense/content.html"